[package]
name = "pecunia"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "^1.3.0"
chrono = { version = "^0.4.31" , features = ["serde"] }
bigdecimal = { version = "^0.4.2", features = ["serde"] }
serde = { version = "^1.0.189", features = ["derive"] }
log = "0.4.20"